// <auto-generated />
using System;
using GISProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GISProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GISProject.Models.GeoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.ToTable("GeoEntities");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GISProject.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Point>("CurrentLocation")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GISProject.Models.PointOfInterest", b =>
                {
                    b.HasBaseType("GISProject.Models.GeoEntity");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TrailId")
                        .HasColumnType("bigint");

                    b.HasIndex("TrailId");

                    b.ToTable("PointsOfInterests");
                });

            modelBuilder.Entity("GISProject.Models.Trail", b =>
                {
                    b.HasBaseType("GISProject.Models.GeoEntity");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<double?>("EstimatedLengthMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrailType")
                        .HasColumnType("integer");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Trails");
                });

            modelBuilder.Entity("GISProject.Models.PointOfInterest", b =>
                {
                    b.HasOne("GISProject.Models.GeoEntity", null)
                        .WithOne()
                        .HasForeignKey("GISProject.Models.PointOfInterest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GISProject.Models.Trail", "Trail")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("TrailId");

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("GISProject.Models.Trail", b =>
                {
                    b.HasOne("GISProject.Models.User", "CreatedByUser")
                        .WithMany("CreatedTrails")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("GISProject.Models.GeoEntity", null)
                        .WithOne()
                        .HasForeignKey("GISProject.Models.Trail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GISProject.Models.User", b =>
                {
                    b.Navigation("CreatedTrails");
                });

            modelBuilder.Entity("GISProject.Models.Trail", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
